/// Standard double-colon tag prefixes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TagPrefix {
    Android,
    Kotlin,
    Cs,
    Topic,
    Difficulty,
    Lang,
    Source,
    Context,
    Bias,
    Testing,
    Architecture,
    Performance,
    Platform,
    Security,
    Networking,
}

impl TagPrefix {
    /// Return the lowercase string form (e.g. `"android"`, `"cs"`).
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Android => "android",
            Self::Kotlin => "kotlin",
            Self::Cs => "cs",
            Self::Topic => "topic",
            Self::Difficulty => "difficulty",
            Self::Lang => "lang",
            Self::Source => "source",
            Self::Context => "context",
            Self::Bias => "bias",
            Self::Testing => "testing",
            Self::Architecture => "architecture",
            Self::Performance => "performance",
            Self::Platform => "platform",
            Self::Security => "security",
            Self::Networking => "networking",
        }
    }
}

/// All valid prefix strings as a static slice.
pub static VALID_PREFIXES: &[&str] = &[
    "android",
    "kotlin",
    "cs",
    "topic",
    "difficulty",
    "lang",
    "source",
    "context",
    "bias",
    "testing",
    "architecture",
    "performance",
    "platform",
    "security",
    "networking",
];

/// Prefixes that denote meta tags.
pub static META_TAG_PREFIXES: &[&str] = &["difficulty::", "lang::", "source::", "context::"];

/// Standalone meta tag values.
pub static META_TAGS: &[&str] = &["atomic"];

/// Number of entries in the tag mapping.
pub const TAG_MAPPING_LEN: usize = 464;

pub(crate) static TAG_MAP: phf::Map<&'static str, &'static str> = phf::phf_map! {
    // === Kotlin: Coroutines ===
    "Kotlin::Coroutines" => "kotlin_coroutines",
    "coroutines" => "kotlin_coroutines",
    "c-kotlin-coroutines-basics" => "kotlin_coroutines",
    "continuation" => "kotlin_coroutines",
    "structured-concurrency" => "kotlin_coroutines",
    // === Kotlin: Flow ===
    "Kotlin::Flow" => "kotlin_flow",
    "flow" => "kotlin_flow",
    "backpressure" => "kotlin_flow",
    "buffer" => "kotlin_flow",
    "conflate" => "kotlin_flow",
    // === Kotlin: Channels ===
    "Kotlin::Channels" => "kotlin_channels",
    "Channels" => "kotlin_channels",
    "channels" => "kotlin_channels",
    "pipelines" => "kotlin_channels",
    // === Kotlin: Dispatchers ===
    "Kotlin::Dispatchers" => "kotlin_dispatchers",
    // === Kotlin: Collections ===
    "collections" => "kotlin_collections",
    "list" => "kotlin_collections",
    "array" => "kotlin_collections",
    "iteration" => "kotlin_collections",
    "iterators" => "kotlin_collections",
    "fold" => "kotlin_collections",
    "ordering" => "kotlin_collections",
    "data-structures" => "kotlin_collections",
    "queues" => "kotlin_collections",
    // === Kotlin: Classes ===
    "Kotlin::Classes" => "kotlin_classes",
    "classes" => "kotlin_classes",
    "data-classes" => "kotlin_classes",
    "sealed-classes" => "kotlin_classes",
    "enums" => "kotlin_classes",
    "nested-class" => "kotlin_classes",
    "inner-class" => "kotlin_classes",
    "anonymous-classes" => "kotlin_classes",
    "singleton" => "kotlin_classes",
    // === Kotlin: Type System ===
    "type-system" => "kotlin_types",
    "types" => "kotlin_types",
    "type-safety" => "kotlin_types",
    "generics" => "kotlin_types",
    "star-projection" => "kotlin_types",
    "null-safety" => "kotlin_types",
    // === Kotlin: Functions ===
    "functions" => "kotlin_functions",
    "lambdas" => "kotlin_functions",
    "higher-order-functions" => "kotlin_functions",
    "inline-functions" => "kotlin_functions",
    "inline" => "kotlin_functions",
    "extensions" => "kotlin_functions",
    "scope-functions" => "kotlin_functions",
    "let" => "kotlin_functions",
    "apply" => "kotlin_functions",
    // === Kotlin: OOP ===
    "inheritance" => "kotlin_oop",
    "interfaces" => "kotlin_oop",
    "polymorphism" => "kotlin_oop",
    "encapsulation" => "kotlin_oop",
    "access-modifiers" => "kotlin_oop",
    "access-control" => "kotlin_oop",
    "visibility" => "kotlin_oop",
    "visibility-modifiers" => "kotlin_oop",
    "modifiers" => "kotlin_oop",
    // === Kotlin: Constructors & Init ===
    "constructors" => "kotlin_initialization",
    "init-block" => "kotlin_initialization",
    "initialization" => "kotlin_initialization",
    // === Kotlin: Delegation ===
    "delegation" => "kotlin_delegation",
    "delegates" => "kotlin_delegation",
    // === Kotlin: Operators & Syntax ===
    "operators" => "kotlin_syntax",
    "syntax" => "kotlin_syntax",
    "control-flow" => "kotlin_syntax",
    "when-expression" => "kotlin_syntax",
    "ranges" => "kotlin_syntax",
    "step" => "kotlin_syntax",
    "destructuring" => "kotlin_syntax",
    "componentN" => "kotlin_syntax",
    "conventions" => "kotlin_syntax",
    // === Kotlin: Equality & Comparison ===
    "equality" => "kotlin_equality",
    "object-comparison" => "kotlin_equality",
    "object-methods" => "kotlin_equality",
    "hash-tables" => "kotlin_equality",
    // === Kotlin: Concurrency ===
    "concurrency" => "kotlin_concurrency",
    "thread-safety" => "kotlin_concurrency",
    "state-machine" => "kotlin_concurrency",
    // === Kotlin: Java Interop ===
    "java" => "kotlin_java_interop",
    "java-interop" => "kotlin_java_interop",
    // === Kotlin: Android ===
    "Android" => "kotlin_android",
    "WorkManager" => "kotlin_android",
    "jetpack-compose" => "kotlin_android",
    "memory-leaks" => "kotlin_android",
    // === Kotlin: General ===
    "Kotlin" => "kotlin_general",
    "Kotlin::Basics" => "kotlin_general",
    "kotlin-features" => "kotlin_general",
    "language-features" => "kotlin_general",
    "c-kotlin" => "kotlin_general",
    "c-kotlin-features" => "kotlin_general",
    // === Kotlin: Functional Programming ===
    "functional-programming" => "kotlin_functional",
    // === Kotlin: Builders ===
    "builders" => "kotlin_builders",
    // === Kotlin: Annotations ===
    "annotations" => "kotlin_annotations",
    // === Kotlin: Error Handling ===
    "error-handling" => "kotlin_error_handling",
    // === Kotlin: Performance ===
    "performance" => "kotlin_performance",
    // === Kotlin: Internals ===
    "compilation" => "kotlin_internals",
    // === Kotlin: Memory ===
    "references" => "kotlin_memory",
    "cleanup" => "kotlin_memory",
    // === Kotlin: Design Patterns ===
    "design" => "kotlin_patterns",
    // === Android: Core Components ===
    "activity-lifecycle" => "android_lifecycle",
    "fragment-lifecycle" => "android_lifecycle",
    "lifecycle" => "android_lifecycle",
    "onresume" => "android_lifecycle",
    "onpause" => "android_lifecycle",
    "savedinstancestate" => "android_lifecycle",
    "activities" => "android_activities",
    "activity" => "android_activities",
    "launch-modes" => "android_activities",
    "task-management" => "android_activities",
    "fragments" => "android_fragments",
    "fragment" => "android_fragments",
    "fragment-transactions" => "android_fragments",
    "backstack" => "android_fragments",
    "services" => "android_services",
    "service" => "android_services",
    "foreground-service" => "android_services",
    "bound-service" => "android_services",
    "intents" => "android_intents",
    "intent" => "android_intents",
    "intent-filters" => "android_intents",
    "pending-intent" => "android_intents",
    "deep-links" => "android_intents",
    "broadcast-receivers" => "android_broadcast",
    "broadcast" => "android_broadcast",
    "broadcasts" => "android_broadcast",
    "content-providers" => "android_content_providers",
    "content-provider" => "android_content_providers",
    // === Android: UI ===
    "views" => "android_views",
    "view" => "android_views",
    "custom-views" => "android_views",
    "view-hierarchy" => "android_views",
    "viewgroup" => "android_views",
    "layouts" => "android_layouts",
    "layout" => "android_layouts",
    "constraint-layout" => "android_layouts",
    "linear-layout" => "android_layouts",
    "recyclerview" => "android_layouts",
    "compose" => "android_compose",
    "composables" => "android_compose",
    "recomposition" => "android_compose",
    "compose-state" => "android_compose",
    "animations" => "android_animations",
    "animation" => "android_animations",
    "property-animation" => "android_animations",
    // === Android: Architecture ===
    "mvvm" => "android_architecture",
    "mvp" => "android_architecture",
    "mvi" => "android_architecture",
    "clean-architecture" => "android_architecture",
    "architecture" => "android_architecture",
    "viewmodel" => "android_viewmodel",
    "view-model" => "android_viewmodel",
    "savedstatehandle" => "android_viewmodel",
    "livedata" => "android_livedata",
    "live-data" => "android_livedata",
    "mutablelivedata" => "android_livedata",
    "databinding" => "android_databinding",
    "data-binding" => "android_databinding",
    "binding-adapters" => "android_databinding",
    // === Android: Jetpack ===
    "navigation" => "android_navigation",
    "nav-controller" => "android_navigation",
    "navigation-component" => "android_navigation",
    "room" => "android_room",
    "room-database" => "android_room",
    "dao" => "android_room",
    "entity" => "android_room",
    "paging" => "android_paging",
    "paging3" => "android_paging",
    "paging-source" => "android_paging",
    "datastore" => "android_datastore",
    "data-store" => "android_datastore",
    "preferences-datastore" => "android_datastore",
    "shared-preferences" => "android_datastore",
    "workmanager" => "android_workmanager",
    "work-manager" => "android_workmanager",
    "worker" => "android_workmanager",
    // === Android: System ===
    "permissions" => "android_permissions",
    "runtime-permissions" => "android_permissions",
    "storage" => "android_storage",
    "scoped-storage" => "android_storage",
    "file-access" => "android_storage",
    "threading" => "android_threading",
    "main-thread" => "android_threading",
    "handler" => "android_threading",
    "looper" => "android_threading",
    "testing" => "android_testing",
    "unit-testing" => "android_testing",
    "instrumented-testing" => "android_testing",
    "espresso" => "android_testing",
    "networking" => "android_networking",
    "retrofit" => "android_networking",
    "okhttp" => "android_networking",
    "debugging" => "android_debugging",
    "profiling" => "android_debugging",
    "memory-profiler" => "android_debugging",
    // === Android: General ===
    "android" => "android_general",
    "android-basics" => "android_general",
    // === CompSci: Design Patterns (GoF) ===
    "singleton-pattern" => "cs_patterns",
    "factory" => "cs_patterns",
    "factory-method" => "cs_patterns",
    "factory-method-pattern" => "cs_patterns",
    "abstract-factory" => "cs_patterns",
    "abstract-factory-pattern" => "cs_patterns",
    "builder" => "cs_patterns",
    "builder-pattern" => "cs_patterns",
    "prototype" => "cs_patterns",
    "prototype-pattern" => "cs_patterns",
    "adapter" => "cs_patterns",
    "adapter-pattern" => "cs_patterns",
    "bridge" => "cs_patterns",
    "bridge-pattern" => "cs_patterns",
    "composite" => "cs_patterns",
    "composite-pattern" => "cs_patterns",
    "decorator" => "cs_patterns",
    "decorator-pattern" => "cs_patterns",
    "facade" => "cs_patterns",
    "facade-pattern" => "cs_patterns",
    "flyweight" => "cs_patterns",
    "flyweight-pattern" => "cs_patterns",
    "proxy" => "cs_patterns",
    "proxy-pattern" => "cs_patterns",
    "chain-of-responsibility" => "cs_patterns",
    "command" => "cs_patterns",
    "command-pattern" => "cs_patterns",
    "interpreter" => "cs_patterns",
    "interpreter-pattern" => "cs_patterns",
    "iterator" => "cs_patterns",
    "iterator-pattern" => "cs_patterns",
    "mediator" => "cs_patterns",
    "mediator-pattern" => "cs_patterns",
    "memento" => "cs_patterns",
    "memento-pattern" => "cs_patterns",
    "observer" => "cs_patterns",
    "observer-pattern" => "cs_patterns",
    "state" => "cs_patterns",
    "state-pattern" => "cs_patterns",
    "strategy" => "cs_patterns",
    "strategy-pattern" => "cs_patterns",
    "template-method" => "cs_patterns",
    "template-method-pattern" => "cs_patterns",
    "visitor" => "cs_patterns",
    "visitor-pattern" => "cs_patterns",
    "gof-patterns" => "cs_patterns",
    "design-patterns" => "cs_patterns",
    "creational-patterns" => "cs_patterns",
    "structural-patterns" => "cs_patterns",
    "behavioral-patterns" => "cs_patterns",
    "behavioral" => "cs_patterns",
    // === CompSci: OOP ===
    "oop" => "cs_oop",
    "oop-principles" => "cs_oop",
    "object-oriented" => "cs_oop",
    "composition" => "cs_oop",
    "aggregation" => "cs_oop",
    "abstraction" => "cs_oop",
    "abstract-classes" => "cs_oop",
    "relationships" => "cs_oop",
    // === CompSci: Architecture ===
    "mvvm-pattern" => "cs_architecture",
    "mvp-pattern" => "cs_architecture",
    "mvi-pattern" => "cs_architecture",
    "clean-code" => "cs_architecture",
    "clean-code-principles" => "cs_architecture",
    "solid" => "cs_architecture",
    "solid-principles" => "cs_architecture",
    "c-architecture-patterns" => "cs_architecture",
    "software-design" => "cs_architecture",
    "c-clean-code" => "cs_architecture",
    // === CompSci: Concurrency ===
    "concurrency-fundamentals" => "cs_concurrency",
    "coroutine" => "cs_concurrency",
    "dispatchers" => "cs_concurrency",
    "threads" => "cs_concurrency",
    "parallel" => "cs_concurrency",
    "parallel-processing" => "cs_concurrency",
    // === CompSci: Data Structures ===
    "data-structures-algorithms" => "cs_data_structures",
    // === CompSci: Algorithms ===
    "algorithms" => "cs_algorithms",
    "c-algorithms" => "cs_algorithms",
    "graph" => "cs_algorithms",
    "graph-algorithms" => "cs_algorithms",
    "dijkstra" => "cs_algorithms",
    "bellman-ford" => "cs_algorithms",
    "floyd-warshall" => "cs_algorithms",
    "mst" => "cs_algorithms",
    "minimum-spanning-tree" => "cs_algorithms",
    "shortest-path" => "cs_algorithms",
    "bfs" => "cs_algorithms",
    "dfs" => "cs_algorithms",
    "topological-sort" => "cs_algorithms",
    "backtracking" => "cs_algorithms",
    "n-queens" => "cs_algorithms",
    "sudoku" => "cs_algorithms",
    "permutations" => "cs_algorithms",
    "combinations" => "cs_algorithms",
    "recursion" => "cs_algorithms",
    "binary-search" => "cs_algorithms",
    "bst" => "cs_algorithms",
    "binary-search-tree" => "cs_algorithms",
    "dynamic-programming" => "cs_algorithms",
    "dp" => "cs_algorithms",
    "memoization" => "cs_algorithms",
    "sorting" => "cs_algorithms",
    "quicksort" => "cs_algorithms",
    "mergesort" => "cs_algorithms",
    "heapsort" => "cs_algorithms",
    "two-pointers" => "cs_algorithms",
    "sliding-window" => "cs_algorithms",
    // === CompSci: Database ===
    "database" => "cs_database",
    "database-fundamentals" => "cs_database",
    "databases" => "cs_database",
    "sql" => "cs_database",
    "sql-join" => "cs_database",
    "join-algorithms" => "cs_database",
    "migration" => "cs_database",
    "schema-evolution" => "cs_database",
    "virtual-tables" => "cs_database",
    "indexing" => "cs_database",
    "normalization" => "cs_database",
    "transactions" => "cs_database",
    "c-database-design" => "cs_database",
    "c-migrations" => "cs_database",
    // === CompSci: Networking / APIs ===
    "http" => "cs_networking",
    "rest" => "cs_networking",
    "graphql" => "cs_networking",
    "api-clients" => "cs_networking",
    "interceptors" => "cs_networking",
    "call-adapter" => "cs_networking",
    "request-deduplication" => "cs_networking",
    "c-http-client" => "cs_networking",
    // === CompSci: Security ===
    "security" => "cs_security",
    "certificate-pinning" => "cs_security",
    "tls" => "cs_security",
    "ssl" => "cs_security",
    "encryption" => "cs_security",
    // === CompSci: OS ===
    "os" => "cs_os",
    "os-fundamentals" => "cs_os",
    "operating-systems" => "cs_os",
    "processes" => "cs_os",
    "memory-management" => "cs_os",
    // === CompSci: Testing ===
    "best-practices" => "cs_testing",
    "flaky-test" => "cs_testing",
    // === CompSci: Types ===
    "data-sealed-classes" => "cs_types",
    // === CompSci: System Design ===
    "system-design" => "cs_system_design",
    "sysdes" => "cs_system_design",
    "scalability" => "cs_system_design",
    "horizontal-scaling" => "cs_system_design",
    "vertical-scaling" => "cs_system_design",
    "load-balancing" => "cs_system_design",
    "sharding" => "cs_system_design",
    "partitioning" => "cs_system_design",
    "cap-theorem" => "cs_system_design",
    "consistency" => "cs_system_design",
    "availability" => "cs_system_design",
    "caching" => "cs_system_design",
    "redis" => "cs_system_design",
    "memcached" => "cs_system_design",
    "message-queues" => "cs_system_design",
    "event-driven" => "cs_system_design",
    "kafka" => "cs_system_design",
    "rabbitmq" => "cs_system_design",
    "microservices" => "cs_system_design",
    "monolith" => "cs_system_design",
    "api-design" => "cs_system_design",
    "rest-api" => "cs_system_design",
    "sql-nosql" => "cs_system_design",
    "database-design" => "cs_system_design",
    // === CompSci: Compilers ===
    "compilers" => "cs_compilers",
    "compiler" => "cs_compilers",
    "parsing" => "cs_compilers",
    "lexing" => "cs_compilers",
    "ast" => "cs_compilers",
    // === CompSci: Distributed Systems ===
    "distributed-systems" => "cs_distributed_systems",
    "distributed" => "cs_distributed_systems",
    "consensus" => "cs_distributed_systems",
    "raft" => "cs_distributed_systems",
    "paxos" => "cs_distributed_systems",
    "replication" => "cs_distributed_systems",
    // === CompSci: General ===
    "cs" => "cs_general",
    "c-cs" => "cs_general",
    "c-computer-science" => "cs_general",
    "theory" => "cs_general",
    // === Cognitive Bias: Probability ===
    "probability-bias" => "bias_probability",
    "illusion-control" => "bias_probability",
    "gambler-fallacy" => "bias_probability",
    "base-rate" => "bias_probability",
    "conjunction-fallacy" => "bias_probability",
    "zero-risk" => "bias_probability",
    "ambiguity-effect" => "bias_probability",
    "texas-sharpshooter" => "bias_probability",
    // === Cognitive Bias: Self-Perception ===
    "self-perception-bias" => "bias_self",
    "dunning-kruger" => "bias_self",
    "overconfidence" => "bias_self",
    "illusion-mind" => "bias_self",
    "illusion-knowledge" => "bias_self",
    "self-deception" => "bias_self",
    "bias-blind-spot" => "bias_self",
    "false-uniqueness" => "bias_self",
    "end-of-history" => "bias_self",
    // === Cognitive Bias: Others-Perception ===
    "others-perception-bias" => "bias_others",
    "fundamental-attribution" => "bias_others",
    "false-consensus" => "bias_others",
    "illusion-transparency" => "bias_others",
    "curse-knowledge" => "bias_others",
    "professional-deformation" => "bias_others",
    // === Cognitive Bias: Decision ===
    "decision-bias" => "bias_decisions",
    "illusion-choice" => "bias_decisions",
    "false-dilemma" => "bias_decisions",
    "sunk-cost" => "bias_decisions",
    "status-quo" => "bias_decisions",
    "omission-bias" => "bias_decisions",
    "framing-effect" => "bias_decisions",
    "planning-fallacy" => "bias_decisions",
    "endowment-effect" => "bias_decisions",
    "anchoring" => "bias_decisions",
    // === Cognitive Bias: Information ===
    "information-bias" => "bias_information",
    "survivorship-bias" => "bias_information",
    "inspection-paradox" => "bias_information",
    "selective-thinking" => "bias_information",
    "fact-fitting" => "bias_information",
    "positive-outcome" => "bias_information",
    "wishful-thinking" => "bias_information",
    "information-cascade" => "bias_information",
    // === Cognitive Bias: Perception Effects ===
    "perception-effect" => "bias_perception",
    "halo-effect" => "bias_perception",
    "primacy-effect" => "bias_perception",
    "recency-effect" => "bias_perception",
    "contrast-effect" => "bias_perception",
    "barnum-effect" => "bias_perception",
    "identifiable-victim" => "bias_perception",
    // === Cognitive Bias: Memory Effects ===
    "memory-effect" => "bias_memory",
    "hindsight-bias" => "bias_memory",
    "retrospective-falsification" => "bias_memory",
    "cryptomnesia" => "bias_memory",
    "telescoping-effect" => "bias_memory",
    "zeigarnik-effect" => "bias_memory",
    "misinformation-effect" => "bias_memory",
    // === Cognitive Bias: Social ===
    "social-bias" => "bias_social",
    "ingroup-favoritism" => "bias_social",
    "outgroup-homogeneity" => "bias_social",
    "bandwagon-effect" => "bias_social",
    "popularity-argument" => "bias_social",
    "normalcy-illusion" => "bias_social",
    // === Cognitive Bias: Argumentation ===
    "argumentation-bias" => "bias_argumentation",
    "ad-hominem" => "bias_argumentation",
    "argument-ignorance" => "bias_argumentation",
    "argument-consequence" => "bias_argumentation",
    "false-inference" => "bias_argumentation",
    "non-sequitur" => "bias_argumentation",
    "denying-antecedent" => "bias_argumentation",
    "affirming-consequent" => "bias_argumentation",
    "straw-man" => "bias_argumentation",
    "begging-question" => "bias_argumentation",
    "appeal-authority" => "bias_argumentation",
    "appeal-tradition" => "bias_argumentation",
    "demagoguery" => "bias_argumentation",
    // === Cognitive Bias: Specific ===
    "specific-bias" => "bias_specific",
    "ad-hoc-hypothesis" => "bias_specific",
    "god-delusion" => "bias_specific",
    "cargo-cult" => "bias_specific",
    "pragmatic-fallacy" => "bias_specific",
    "regressive-fallacy" => "bias_specific",
    "anecdotal-evidence" => "bias_specific",
    "faith-science" => "bias_specific",
    "hawthorne-effect" => "bias_specific",
    "observer-expectancy" => "bias_specific",
    "functional-fixedness" => "bias_specific",
    // === Cognitive Bias: General ===
    "cognitive-bias" => "cognitive_bias",
    "bias" => "cognitive_bias",
};

/// Variant -> normalized canonical tag lookup.
pub fn lookup_tag(variant: &str) -> Option<&'static str> {
    TAG_MAP.get(variant).copied()
}

/// All canonical Kotlin topic tags.
pub static KOTLIN_TOPIC_TAGS: &[&str] = &[
    "kotlin_coroutines",
    "kotlin_flow",
    "kotlin_channels",
    "kotlin_dispatchers",
    "kotlin_collections",
    "kotlin_classes",
    "kotlin_types",
    "kotlin_functions",
    "kotlin_oop",
    "kotlin_initialization",
    "kotlin_delegation",
    "kotlin_syntax",
    "kotlin_equality",
    "kotlin_concurrency",
    "kotlin_java_interop",
    "kotlin_android",
    "kotlin_general",
    "kotlin_functional",
    "kotlin_builders",
    "kotlin_annotations",
    "kotlin_error_handling",
    "kotlin_performance",
    "kotlin_internals",
    "kotlin_memory",
    "kotlin_patterns",
];

/// All canonical Android topic tags.
pub static ANDROID_TOPIC_TAGS: &[&str] = &[
    "android_lifecycle",
    "android_activities",
    "android_fragments",
    "android_services",
    "android_intents",
    "android_broadcast",
    "android_content_providers",
    "android_views",
    "android_layouts",
    "android_compose",
    "android_animations",
    "android_architecture",
    "android_viewmodel",
    "android_livedata",
    "android_databinding",
    "android_navigation",
    "android_room",
    "android_paging",
    "android_datastore",
    "android_workmanager",
    "android_permissions",
    "android_storage",
    "android_threading",
    "android_testing",
    "android_networking",
    "android_debugging",
    "android_general",
];

/// All canonical CompSci topic tags.
pub static COMPSCI_TOPIC_TAGS: &[&str] = &[
    "cs_patterns",
    "cs_oop",
    "cs_architecture",
    "cs_concurrency",
    "cs_data_structures",
    "cs_algorithms",
    "cs_database",
    "cs_networking",
    "cs_system_design",
    "cs_distributed_systems",
    "cs_security",
    "cs_os",
    "cs_testing",
    "cs_types",
    "cs_compilers",
    "cs_general",
];

/// All canonical Cognitive Bias topic tags.
pub static COGNITIVE_BIAS_TOPIC_TAGS: &[&str] = &[
    "cognitive_bias",
    "bias_probability",
    "bias_self",
    "bias_others",
    "bias_decisions",
    "bias_information",
    "bias_perception",
    "bias_memory",
    "bias_social",
    "bias_argumentation",
    "bias_specific",
];

/// Check if a tag is a known topic tag (O(1) lookup).
pub fn is_known_topic_tag(tag: &str) -> bool {
    KOTLIN_TOPIC_TAGS.contains(&tag)
        || ANDROID_TOPIC_TAGS.contains(&tag)
        || COMPSCI_TOPIC_TAGS.contains(&tag)
        || COGNITIVE_BIAS_TOPIC_TAGS.contains(&tag)
}

/// Valid difficulty meta tag values.
pub static VALID_DIFFICULTIES: &[&str] =
    &["difficulty::easy", "difficulty::medium", "difficulty::hard"];

/// Valid language meta tag values.
pub static VALID_LANGS: &[&str] = &["lang::en", "lang::ru"];

/// Topic prefixes in underscore format used internally.
pub(crate) static TOPIC_PREFIXES: &[&str] = &["kotlin_", "android_", "cs_", "bias_"];
